//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schelet_Server
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class JucatorJoc
    {
        public int id { get; set; }
        public Nullable<int> idJucator { get; set; }
        public Nullable<int> idJoc { get; set; }
        public Nullable<int> numarcuvinte { get; set; }
        public string cuvant1 { get; set; }
        public string cuvant2 { get; set; }
        public string cuvant3 { get; set; }
        public Nullable<int> punctaj { get; set; }
    
        public virtual Joc Joc { get; set; }
        public virtual Jucator Jucator { get; set; }
    }
}
