//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schelet_Server
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class JocJucator
    {
        public int id { get; set; }
        public Nullable<int> idjoc { get; set; }
        public Nullable<int> idjucator { get; set; }
        public Nullable<int> poz1 { get; set; }
        public Nullable<int> poz2 { get; set; }
        public Nullable<int> pozaleasa { get; set; }
        public Nullable<int> ales { get; set; }
    
        public virtual Joc Joc { get; set; }
        public virtual Jucator Jucator { get; set; }
    }
}
