//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schelet_Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JumpingEntitiesCuPunctaj : DbContext
    {
        public JumpingEntitiesCuPunctaj()
            : base("name=JumpingEntitiesCuPunctaj")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Juriu> Jurius { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<PunctajPartcipant> PunctajPartcipants { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
