//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schelet_Server
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class PunctajPartcipant
    {
        public int id { get; set; }
        public Nullable<int> lungime { get; set; }
        public Nullable<int> stil { get; set; }
        public Nullable<int> aterizare { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
