//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablerest
    {
        public int id { get; set; }
        public Nullable<int> id_participant1 { get; set; }
        public Nullable<int> id_participant2 { get; set; }
        public string poztitie_barcuta1 { get; set; }
        public string poztie_barcuta2 { get; set; }
        public Nullable<int> numar_incercari_jucator1 { get; set; }
        public Nullable<int> numar_incercari_jucator2 { get; set; }
        public Nullable<int> castigator_joc { get; set; }
    }
}
