//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JocJucator
    {
        public int id { get; set; }
        public Nullable<int> idjoc { get; set; }
        public Nullable<int> idjucator { get; set; }
        public string cuvant { get; set; }
        public string mapare { get; set; }
        public Nullable<int> punctaj { get; set; }
        public string literealese { get; set; }
        public Nullable<int> ales { get; set; }
    }
}
